### ISSUE TITLE
QCP work with clusters

### ISSUE THREAD

**Issue by margaret-aaron-123456** [FRC-836/836-Library#27]
The QCP currently in the library doesn't allow use with clusters without a cluster to array.

**Comment by Cheeto836** [comment]
After investigation, the following information has been learned.

Not much is gained by allowing clusters to be retrieved from QCP. The cluster out would still need to be typecast to contain the appropriate number of elements.

On writing a cluster to a QCP file, there is a lot of uncertainty in how it should be done. Should each element be written such that it is a QCP value itself, or should the whole cluster be stored as an array? 

Most of the initially perceived benefits of allowing QCPs to interact with clusters is lost in the way the clusters would have to be handled.
